# Generated by Django 5.0.1 on 2024-04-20 03:59

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Users",
            fields=[
                (
                    "user_id",
                    models.CharField(
                        default=None, max_length=60, primary_key=True, serialize=False
                    ),
                ),
                (
                    "user_name",
                    models.CharField(
                        blank=True, default=None, max_length=100, null=True
                    ),
                ),
                (
                    "user_email",
                    models.CharField(
                        blank=True, default=None, max_length=100, null=True
                    ),
                ),
                (
                    "user_phone_no",
                    models.CharField(
                        blank=True, default=None, max_length=100, null=True
                    ),
                ),
                ("user_password", models.CharField(max_length=128)),
                ("forget_password_token", models.CharField(default="", max_length=100)),
                ("user_is_active", models.CharField(default=True, max_length=100)),
                ("user_created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "Users_information_tb",
            },
        ),
    ]
