# Generated by Django 5.0.1 on 2024-04-20 03:59

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AdminUsers",
            fields=[
                (
                    "admin_user_id",
                    models.CharField(
                        default=None, max_length=60, primary_key=True, serialize=False
                    ),
                ),
                (
                    "admin_user_name",
                    models.CharField(
                        blank=True, default=None, max_length=100, null=True
                    ),
                ),
                (
                    "admin_user_email",
                    models.CharField(
                        blank=True, default=None, max_length=100, null=True
                    ),
                ),
                (
                    "admin_user_phone_no",
                    models.CharField(
                        blank=True, default=None, max_length=100, null=True
                    ),
                ),
                ("admin_user_password", models.CharField(default=None, max_length=128)),
                (
                    "admin_user_is_active",
                    models.CharField(default=True, max_length=100),
                ),
                ("admin_user_created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "admin_users_information_tb",
            },
        ),
    ]
