# Generated by Django 5.0.1 on 2024-04-20 03:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("products", "0001_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="address",
            fields=[
                (
                    "address_id",
                    models.CharField(max_length=60, primary_key=True, serialize=False),
                ),
                (
                    "house_no",
                    models.CharField(
                        blank=True, default=None, max_length=10000, null=True
                    ),
                ),
                (
                    "residence_name",
                    models.CharField(
                        blank=True, default=None, max_length=10000, null=True
                    ),
                ),
                (
                    "landmark",
                    models.CharField(
                        blank=True, default=None, max_length=10000, null=True
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        blank=True, default=None, max_length=10000, null=True
                    ),
                ),
                (
                    "pin_code",
                    models.CharField(
                        blank=True, default=None, max_length=10000, null=True
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        blank=True, default=None, max_length=10000, null=True
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        blank=True, default=None, max_length=10000, null=True
                    ),
                ),
                (
                    "deliver_to_whom",
                    models.CharField(
                        blank=True, default=None, max_length=10000, null=True
                    ),
                ),
                (
                    "deliver_to_contact",
                    models.CharField(
                        blank=True, default=None, max_length=10000, null=True
                    ),
                ),
                (
                    "ship_to_different",
                    models.CharField(
                        blank=True, default=None, max_length=10000, null=True
                    ),
                ),
                (
                    "f_name_2",
                    models.CharField(
                        blank=True, default=None, max_length=10000, null=True
                    ),
                ),
                (
                    "l_name_2",
                    models.CharField(
                        blank=True, default=None, max_length=10000, null=True
                    ),
                ),
                (
                    "email_2",
                    models.CharField(
                        blank=True, default=None, max_length=10000, null=True
                    ),
                ),
                (
                    "country_2",
                    models.CharField(
                        blank=True, default=None, max_length=10000, null=True
                    ),
                ),
                (
                    "street_address_2",
                    models.CharField(
                        blank=True, default=None, max_length=10000, null=True
                    ),
                ),
                (
                    "town_2",
                    models.CharField(
                        blank=True, default=None, max_length=10000, null=True
                    ),
                ),
                (
                    "state_2",
                    models.CharField(
                        blank=True, default=None, max_length=10000, null=True
                    ),
                ),
                (
                    "postcode_2",
                    models.CharField(
                        blank=True, default=None, max_length=10000, null=True
                    ),
                ),
                ("address_created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user_fk",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="users.users"
                    ),
                ),
            ],
            options={
                "db_table": "address_information_tb",
            },
        ),
        migrations.CreateModel(
            name="cart_item",
            fields=[
                (
                    "cart_items_id",
                    models.CharField(
                        default=None, max_length=60, primary_key=True, serialize=False
                    ),
                ),
                ("items_quantity", models.CharField(default=None, max_length=60)),
                ("cart_created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "product_fk",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="products.product",
                    ),
                ),
                (
                    "product_image_fk",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="products.product_image",
                    ),
                ),
                (
                    "product_price_fk",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="products.product_price",
                    ),
                ),
                (
                    "user_fk",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.users",
                    ),
                ),
            ],
            options={
                "db_table": "cart_items_information_tb",
            },
        ),
        migrations.CreateModel(
            name="shipping",
            fields=[
                (
                    "shipping_id",
                    models.CharField(
                        default=None, max_length=60, primary_key=True, serialize=False
                    ),
                ),
                (
                    "address_fk",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="shipping.address",
                    ),
                ),
                (
                    "cart_fk",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="shipping.cart_item",
                    ),
                ),
                (
                    "user_fk",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.users",
                    ),
                ),
            ],
            options={
                "db_table": "shipping_information_tb",
            },
        ),
    ]
