# Generated by Django 5.0.1 on 2024-05-08 07:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("shipping", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="address",
            name="address_created_at",
        ),
        migrations.RemoveField(
            model_name="address",
            name="country_2",
        ),
        migrations.RemoveField(
            model_name="address",
            name="email_2",
        ),
        migrations.RemoveField(
            model_name="address",
            name="f_name_2",
        ),
        migrations.RemoveField(
            model_name="address",
            name="l_name_2",
        ),
        migrations.RemoveField(
            model_name="address",
            name="postcode_2",
        ),
        migrations.RemoveField(
            model_name="address",
            name="ship_to_different",
        ),
        migrations.RemoveField(
            model_name="address",
            name="state_2",
        ),
        migrations.RemoveField(
            model_name="address",
            name="street_address_2",
        ),
        migrations.RemoveField(
            model_name="address",
            name="town_2",
        ),
    ]
